<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Next slide</name>
   <tag></tag>
   <elementGuidId>f69ebf81-46ab-478e-be8d-2cfcf7d6aeac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-desktop-herotator']/div/div/div/div[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-next-rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>94a8dc93-2ae0-4c72-9e38-d10e94842f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-next-rounded</value>
      <webElementGuid>c0dedbd3-18fb-494c-b4e3-8fe4853dad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next slide</value>
      <webElementGuid>6b3410d2-905f-4a16-85c6-ca0abd7ed79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-desktop-herotator&quot;)/div[@class=&quot;a-begin a-carousel-container a-carousel-display-single a-carousel-transition-slideCircular gw-desktop-herotator a-carousel-initialized&quot;]/div[@class=&quot;a-row a-carousel-controls a-carousel-row a-carousel-has-buttons a-carousel-overlay-buttons a-carousel-rounded-buttons&quot;]/div[@class=&quot;a-carousel-row-inner&quot;]/div[@class=&quot;a-carousel-col a-carousel-right celwidget&quot;]/a[@class=&quot;a-carousel-goto-nextpage&quot;]/i[@class=&quot;a-icon a-icon-next-rounded&quot;]</value>
      <webElementGuid>da68878e-97b2-4631-9f81-46159f277b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-desktop-herotator']/div/div/div/div[3]/a/i</value>
      <webElementGuid>de06ab4b-62b7-4c9d-bfb7-aea6d6722a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/i</value>
      <webElementGuid>c15ae682-e7ba-4786-b21d-f9e56be43b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'Next slide' or . = 'Next slide')]</value>
      <webElementGuid>91dd8fd0-0542-4edf-97b3-bc655b99304b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
