<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Previous slide</name>
   <tag></tag>
   <elementGuidId>23b05080-18d5-4508-8626-c1c940714eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-desktop-herotator']/div/div/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.a-icon.a-icon-previous-rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8e5913de-32fb-4051-a2ca-a85cb0c48814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-icon a-icon-previous-rounded</value>
      <webElementGuid>92191085-d8dd-4ef7-9728-0a95c16fbd16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Previous slide</value>
      <webElementGuid>1379f867-d3da-499d-b2e5-89501950503b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-desktop-herotator&quot;)/div[@class=&quot;a-begin a-carousel-container a-carousel-display-single a-carousel-transition-slideCircular gw-desktop-herotator a-carousel-initialized&quot;]/div[@class=&quot;a-row a-carousel-controls a-carousel-row a-carousel-has-buttons a-carousel-overlay-buttons a-carousel-rounded-buttons&quot;]/div[@class=&quot;a-carousel-row-inner&quot;]/div[@class=&quot;a-carousel-col a-carousel-left celwidget&quot;]/a[@class=&quot;a-carousel-goto-prevpage&quot;]/i[@class=&quot;a-icon a-icon-previous-rounded&quot;]</value>
      <webElementGuid>6b11acf7-cd2f-4f1a-b876-fbe77a0965b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-desktop-herotator']/div/div/div/div/a/i</value>
      <webElementGuid>52c04e42-f288-4ae5-b0b9-b3cdab9c7e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a/i</value>
      <webElementGuid>36e08f1d-bbc4-4257-b13e-5f306a0fa775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'Previous slide' or . = 'Previous slide')]</value>
      <webElementGuid>b16fc139-cb96-4a76-a11b-017d509f9cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
